version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./app/saved_model
        target: /app/saved_model

  test:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["python", "-m", "unittest", "discover", "-s", "tests"]
