# Generated by Django 4.0.1 on 2022-03-06 22:36

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Datetime when the object was created.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Datetime when the object was last updated.')),
                ('title', models.CharField(blank=True, help_text='Article title, up to 255 characters.', max_length=255, null=True, verbose_name='Article Title')),
                ('published', models.BooleanField(default=False, help_text='Was this article published?')),
                ('pubmed_id', models.IntegerField(blank=True, help_text='PubMed ID of the article.', null=True)),
                ('doi', models.CharField(blank=True, help_text='DOI code of the article.', max_length=64)),
                ('article_url', models.URLField(blank=True, null=True)),
                ('pub_year', models.IntegerField(blank=True, help_text="The article's publication year.", null=True)),
                ('published_authors', models.TextField(blank=True, help_text="A list of authors' names. Up to 256 characters.", max_length=256)),
                ('article_author_email', models.CharField(blank=True, help_text="A list of the article's authors' emails. Up to 256 characters.", max_length=255)),
                ('journal', models.TextField(blank=True, help_text='Title of the journal the article is published in.', max_length=256)),
                ('abstract', models.TextField(blank=True, help_text='An abstract of the article.')),
                ('article_type', models.CharField(blank=True, choices=[('Original', 'Original'), ('Review', 'Review')], help_text='Article type.', max_length=8)),
                ('study_type', models.CharField(blank=True, choices=[('Case Report', 'Case Report'), ('Case Series', 'Case Series'), ('Observational Study', 'Observational Study'), ('Clinical Trial', 'Clinical Trial'), ('Other', 'Other')], default='Case Report', help_text='Article study type.', max_length=32)),
                ('number_of_patients', models.IntegerField(blank=True, null=True)),
                ('article_patient_number', models.CharField(blank=True, help_text='Patient # or Id in the Article. Up to 64 characters.', max_length=64)),
                ('article_language', models.CharField(blank=True, choices=[('ab', 'Abkhazian'), ('aa', 'Afar'), ('af', 'Afrikaans'), ('ak', 'Akan'), ('sq', 'Albanian'), ('am', 'Amharic'), ('ar', 'Arabic'), ('an', 'Aragonese'), ('hy', 'Armenian'), ('as', 'Assamese'), ('av', 'Avaric'), ('ae', 'Avestan'), ('ay', 'Aymara'), ('az', 'Azerbaijani'), ('bm', 'Bambara'), ('ba', 'Bashkir'), ('eu', 'Basque'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('bh', 'Bihari languages'), ('bi', 'Bislama'), ('nb', 'Bokmål, Norwegian; Norwegian Bokmål'), ('bs', 'Bosnian'), ('br', 'Breton'), ('bg', 'Bulgarian'), ('my', 'Burmese'), ('ca', 'Catalan; Valencian'), ('km', 'Central Khmer'), ('ch', 'Chamorro'), ('ce', 'Chechen'), ('ny', 'Chichewa; Chewa; Nyanja'), ('zh', 'Chinese'), ('cu', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'), ('cv', 'Chuvash'), ('kw', 'Cornish'), ('co', 'Corsican'), ('cr', 'Cree'), ('hr', 'Croatian'), ('cs', 'Czech'), ('da', 'Danish'), ('dv', 'Divehi; Dhivehi; Maldivian'), ('nl', 'Dutch; Flemish'), ('dz', 'Dzongkha'), ('en', 'English'), ('eo', 'Esperanto'), ('et', 'Estonian'), ('ee', 'Ewe'), ('fo', 'Faroese'), ('fj', 'Fijian'), ('fi', 'Finnish'), ('fr', 'French'), ('ff', 'Fulah'), ('gd', 'Gaelic; Scottish Gaelic'), ('gl', 'Galician'), ('lg', 'Ganda'), ('ka', 'Georgian'), ('de', 'German'), ('el', 'Greek, Modern (1453-)'), ('gn', 'Guarani'), ('gu', 'Gujarati'), ('ht', 'Haitian; Haitian Creole'), ('ha', 'Hausa'), ('he', 'Hebrew'), ('hz', 'Herero'), ('hi', 'Hindi'), ('ho', 'Hiri Motu'), ('hu', 'Hungarian'), ('is', 'Icelandic'), ('io', 'Ido'), ('ig', 'Igbo'), ('id', 'Indonesian'), ('ia', 'Interlingua (International Auxiliary Language Association)'), ('ie', 'Interlingue; Occidental'), ('iu', 'Inuktitut'), ('ik', 'Inupiaq'), ('ga', 'Irish'), ('it', 'Italian'), ('ja', 'Japanese'), ('jv', 'Javanese'), ('kl', 'Kalaallisut; Greenlandic'), ('kn', 'Kannada'), ('kr', 'Kanuri'), ('ks', 'Kashmiri'), ('kk', 'Kazakh'), ('ki', 'Kikuyu; Gikuyu'), ('rw', 'Kinyarwanda'), ('ky', 'Kirghiz; Kyrgyz'), ('kv', 'Komi'), ('kg', 'Kongo'), ('ko', 'Korean'), ('kj', 'Kuanyama; Kwanyama'), ('ku', 'Kurdish'), ('lo', 'Lao'), ('la', 'Latin'), ('lv', 'Latvian'), ('li', 'Limburgan; Limburger; Limburgish'), ('ln', 'Lingala'), ('lt', 'Lithuanian'), ('lu', 'Luba-Katanga'), ('lb', 'Luxembourgish; Letzeburgesch'), ('mk', 'Macedonian'), ('mg', 'Malagasy'), ('ms', 'Malay'), ('ml', 'Malayalam'), ('mt', 'Maltese'), ('gv', 'Manx'), ('mi', 'Maori'), ('mr', 'Marathi'), ('mh', 'Marshallese'), ('mn', 'Mongolian'), ('na', 'Nauru'), ('nv', 'Navajo; Navaho'), ('nd', 'Ndebele, North; North Ndebele'), ('nr', 'Ndebele, South; South Ndebele'), ('ng', 'Ndonga'), ('ne', 'Nepali'), ('se', 'Northern Sami'), ('nn', 'Norwegian Nynorsk; Nynorsk, Norwegian'), ('no', 'Norwegian'), ('oc', 'Occitan (post 1500)'), ('oj', 'Ojibwa'), ('or', 'Oriya'), ('om', 'Oromo'), ('os', 'Ossetian; Ossetic'), ('pi', 'Pali'), ('pa', 'Panjabi; Punjabi'), ('fa', 'Persian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ps', 'Pushto; Pashto'), ('qu', 'Quechua'), ('ro', 'Romanian; Moldavian; Moldovan'), ('rm', 'Romansh'), ('rn', 'Rundi'), ('ru', 'Russian'), ('sm', 'Samoan'), ('sg', 'Sango'), ('sa', 'Sanskrit'), ('sc', 'Sardinian'), ('sr', 'Serbian'), ('sn', 'Shona'), ('ii', 'Sichuan Yi; Nuosu'), ('sd', 'Sindhi'), ('si', 'Sinhala; Sinhalese'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('so', 'Somali'), ('st', 'Sotho, Southern'), ('es', 'Spanish; Castilian'), ('su', 'Sundanese'), ('sw', 'Swahili'), ('ss', 'Swati'), ('sv', 'Swedish'), ('tl', 'Tagalog'), ('ty', 'Tahitian'), ('tg', 'Tajik'), ('ta', 'Tamil'), ('tt', 'Tatar'), ('te', 'Telugu'), ('th', 'Thai'), ('bo', 'Tibetan'), ('ti', 'Tigrinya'), ('to', 'Tonga (Tonga Islands)'), ('ts', 'Tsonga'), ('tn', 'Tswana'), ('tr', 'Turkish'), ('tk', 'Turkmen'), ('tw', 'Twi'), ('ug', 'Uighur; Uyghur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('ve', 'Venda'), ('vi', 'Vietnamese'), ('vo', 'Volapük'), ('wa', 'Walloon'), ('cy', 'Welsh'), ('fy', 'Western Frisian'), ('wo', 'Wolof'), ('xh', 'Xhosa'), ('yi', 'Yiddish'), ('yo', 'Yoruba'), ('za', 'Zhuang; Chuang'), ('zu', 'Zulu')], max_length=2)),
                ('full_text_available', models.BooleanField(blank=True, default=False, help_text='Is Full Text Available? (Yes or No).', null=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, help_text='A list, up to 16, of image names (each up to 64 chars long).', max_length=16, null=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Datetime when the object was created.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Datetime when the object was last updated.')),
                ('treatment_gestational_age', models.CharField(blank=True, choices=[('UNKNOWN', 'UNKNOWN'), ('1 Week', '1 Week'), ('2 Weeks', '2 Weeks'), ('3 Weeks', '3 Weeks'), ('4 Weeks', '4 Weeks'), ('5 Weeks', '5 Weeks'), ('6 Weeks', '6 Weeks'), ('7 Weeks', '7 Weeks'), ('8 Weeks', '8 Weeks'), ('9 Weeks', '9 Weeks'), ('10 Weeks', '10 Weeks'), ('11 Weeks', '11 Weeks'), ('12 Weeks', '12 Weeks'), ('13 Weeks', '13 Weeks'), ('14 Weeks', '14 Weeks'), ('15 Weeks', '15 Weeks'), ('16 Weeks', '16 Weeks'), ('17 Weeks', '17 Weeks'), ('18 Weeks', '18 Weeks'), ('19 Weeks', '19 Weeks'), ('20 Weeks', '20 Weeks'), ('21 Weeks', '21 Weeks'), ('22 Weeks', '22 Weeks'), ('23 Weeks', '23 Weeks'), ('24 Weeks', '24 Weeks'), ('25 Weeks', '25 Weeks'), ('26 Weeks', '26 Weeks'), ('27 Weeks', '27 Weeks'), ('28 Weeks', '28 Weeks'), ('29 Weeks', '29 Weeks'), ('30 Weeks', '30 Weeks'), ('31 Weeks', '31 Weeks'), ('32 Weeks', '32 Weeks'), ('33 Weeks', '3 Weeks'), ('34 Weeks', '34 Weeks'), ('35 Weeks', '35 Weeks'), ('36 Weeks', '36 Weeks'), ('37 Weeks', '37 Weeks'), ('38 Weeks', '38 Weeks'), ('39 Weeks', '39 Weeks'), ('40 Weeks', '40 Weeks'), ('41 Weeks', '41 Weeks'), ('42 Weeks', '42 Weeks'), ('42 Weeks', '42 Weeks')], help_text='The gestational age in week at the time of the treatment.', max_length=16, null=True)),
                ('delivery_gestational_age', models.CharField(blank=True, choices=[('UNKNOWN', 'UNKNOWN'), ('1 Week', '1 Week'), ('2 Weeks', '2 Weeks'), ('3 Weeks', '3 Weeks'), ('4 Weeks', '4 Weeks'), ('5 Weeks', '5 Weeks'), ('6 Weeks', '6 Weeks'), ('7 Weeks', '7 Weeks'), ('8 Weeks', '8 Weeks'), ('9 Weeks', '9 Weeks'), ('10 Weeks', '10 Weeks'), ('11 Weeks', '11 Weeks'), ('12 Weeks', '12 Weeks'), ('13 Weeks', '13 Weeks'), ('14 Weeks', '14 Weeks'), ('15 Weeks', '15 Weeks'), ('16 Weeks', '16 Weeks'), ('17 Weeks', '17 Weeks'), ('18 Weeks', '18 Weeks'), ('19 Weeks', '19 Weeks'), ('20 Weeks', '20 Weeks'), ('21 Weeks', '21 Weeks'), ('22 Weeks', '22 Weeks'), ('23 Weeks', '23 Weeks'), ('24 Weeks', '24 Weeks'), ('25 Weeks', '25 Weeks'), ('26 Weeks', '26 Weeks'), ('27 Weeks', '27 Weeks'), ('28 Weeks', '28 Weeks'), ('29 Weeks', '29 Weeks'), ('30 Weeks', '30 Weeks'), ('31 Weeks', '31 Weeks'), ('32 Weeks', '32 Weeks'), ('33 Weeks', '3 Weeks'), ('34 Weeks', '34 Weeks'), ('35 Weeks', '35 Weeks'), ('36 Weeks', '36 Weeks'), ('37 Weeks', '37 Weeks'), ('38 Weeks', '38 Weeks'), ('39 Weeks', '39 Weeks'), ('40 Weeks', '40 Weeks'), ('41 Weeks', '41 Weeks'), ('42 Weeks', '42 Weeks'), ('42 Weeks', '42 Weeks')], max_length=16, null=True)),
                ('outcome', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='report',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='report',
            name='age',
        ),
        migrations.RemoveField(
            model_name='report',
            name='article_author_email',
        ),
        migrations.RemoveField(
            model_name='report',
            name='article_language',
        ),
        migrations.RemoveField(
            model_name='report',
            name='article_patient_number',
        ),
        migrations.RemoveField(
            model_name='report',
            name='article_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='article_url',
        ),
        migrations.RemoveField(
            model_name='report',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='report',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='report',
            name='full_text_available',
        ),
        migrations.RemoveField(
            model_name='report',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='report',
            name='number_of_patients',
        ),
        migrations.RemoveField(
            model_name='report',
            name='pregnant',
        ),
        migrations.RemoveField(
            model_name='report',
            name='pub_year',
        ),
        migrations.RemoveField(
            model_name='report',
            name='published',
        ),
        migrations.RemoveField(
            model_name='report',
            name='published_authors',
        ),
        migrations.RemoveField(
            model_name='report',
            name='pubmed_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='report',
            name='study_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorited_clinical_trials',
            field=models.ManyToManyField(blank=True, help_text='List of ClinicalTrials the user is interested in.', related_name='+', to='core.ClinicalTrial'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorited_events',
            field=models.ManyToManyField(blank=True, help_text='List of Events the user is interested in.', related_name='+', to='core.Event'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PAUSED', 'PAUSED'), ('BANNED', 'BANNED')], default='ACTIVE', help_text='This can be used to disable the user.', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.ForeignKey(blank=True, help_text='User that created this Report.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Datetime when the object was created.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Datetime when the object was last updated.')),
                ('age', models.IntegerField(blank=True, help_text='The exact age of the patient at the time of the Report.', null=True)),
                ('age_group', models.CharField(blank=True, choices=[('<1 year', '<1 year'), ('1-5 years', '1-5 years'), ('6-10 years', '6-10 years'), ('11-15 years', '11-15 years'), ('16-20 years', '16-20 years'), ('21-30 years', '21-30 years'), ('31-40 years', '31-40 years'), ('41-50 years', '41-50 years'), ('51-60 years', '51-60 years'), ('61-70 years', '61-70 years'), ('71-80 years', '71-80 years'), ('81-89 years', '81-89 years'), ('90+ years', '90+ years')], max_length=11)),
                ('ethnicity', models.CharField(blank=True, choices=[('Hispanic/Latino', 'Hispanic/Latino'), ('Not Hispanic/Latino', 'Not Hispanic/Latino')], max_length=19, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Not specified', 'Not specified')], max_length=64)),
                ('pregnant', models.BooleanField(default=False, help_text='Was the patient pregnant at the time of test.')),
                ('other_coinfections', models.CharField(blank=True, help_text='Up to 255 characters long.', max_length=255)),
                ('pregnancy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.pregnancy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Neonate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Datetime when the object was created.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Datetime when the object was last updated.')),
                ('diagnosed_with_disease', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not tested', 'Not tested')], max_length=16, null=True)),
                ('abnormalities_or_defects', models.TextField(blank=True, null=True)),
                ('other_outcome_details', models.TextField(blank=True, null=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.pregnancy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='favorited_articles',
            field=models.ManyToManyField(blank=True, help_text='List of Articles the user is interested in.', related_name='+', to='core.Article'),
        ),
        migrations.AddField(
            model_name='report',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.article'),
        ),
        migrations.AddField(
            model_name='report',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.patient'),
        ),
    ]
