# Generated by Django 4.0.1 on 2022-03-08 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_update_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseEventsOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, choices=[('Death', 'Death'), ('Life-threatening', 'Life-threatening'), ('Hospitalization (initial or prolonged)', 'Hospitalization (initial or prolonged)'), ('Disability or Permanent Damage', 'Disability or Permanent Damage'), ('Congenital Anomaly/Birth Defects', 'Congenital Anomaly/Birth Defects'), ('Other Serious or Important Medical Events', 'Other Serious or Important Medical Events'), ('Required Intervention to Prevent Permanent Impairment/Damage', 'Required Intervention to Prevent Permanent Impairment/Damage'), ('Non-Serious Medical Event', 'Non-Serious Medical Event')], max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comorbidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='regimen',
            old_name='approximate_duration',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='organisms',
        ),
        migrations.RemoveField(
            model_name='report',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='report',
            name='article',
        ),
        migrations.RemoveField(
            model_name='report',
            name='asthma',
        ),
        migrations.RemoveField(
            model_name='report',
            name='author',
        ),
        migrations.RemoveField(
            model_name='report',
            name='cardiovascular_disease',
        ),
        migrations.RemoveField(
            model_name='report',
            name='chronic_liver_disease',
        ),
        migrations.RemoveField(
            model_name='report',
            name='chronic_renal_disease',
        ),
        migrations.RemoveField(
            model_name='report',
            name='created',
        ),
        migrations.RemoveField(
            model_name='report',
            name='diabetes_mellitus',
        ),
        migrations.RemoveField(
            model_name='report',
            name='hiv',
        ),
        migrations.RemoveField(
            model_name='report',
            name='hypertension',
        ),
        migrations.RemoveField(
            model_name='report',
            name='immunosuppressant_drugs',
        ),
        migrations.RemoveField(
            model_name='report',
            name='intellectual_disability',
        ),
        migrations.RemoveField(
            model_name='report',
            name='lung_disease',
        ),
        migrations.RemoveField(
            model_name='report',
            name='other_comorbid',
        ),
        migrations.RemoveField(
            model_name='report',
            name='other_immunodeficiency',
        ),
        migrations.RemoveField(
            model_name='report',
            name='smoker',
        ),
        migrations.RemoveField(
            model_name='report',
            name='status',
        ),
        migrations.RemoveField(
            model_name='report',
            name='unknown',
        ),
        migrations.RemoveField(
            model_name='report',
            name='updated',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinicaltrials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='sponsor_type',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='study_type',
            field=models.CharField(blank=True, choices=[('Interventional', 'Interventional'), ('Observational', 'Observational'), ('Patient registries', 'Patient registries'), ('Expanded access', 'Expanded access')], default='Other', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='is_tuberculosis_resistant',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='drugs',
            field=models.ManyToManyField(blank=True, help_text='What drug(s) did you use in a new way?', related_name='reports_drugs', to='core.Drug'),
        ),
        migrations.CreateModel(
            name='WhyNewWayAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=256, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_new_way', to='core.report')),
            ],
        ),
        migrations.CreateModel(
            name='HowDiagnosisAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='how_diagnosis', to='core.report')),
            ],
        ),
        migrations.CreateModel(
            name='CureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Datetime when the object was created.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Datetime when the object was last updated.')),
                ('anonymous', models.BooleanField(default=False)),
                ('flagged', models.BooleanField(default=False)),
                ('reminder', models.BooleanField(default=False)),
                ('when_reminder', models.CharField(blank=True, choices=[('No reminder', 'No reminder'), ('1 week', '1 week'), ('2 weeks', '2 weeks'), ('3 weeks', '3 weeks'), ('1 month', '1 month'), ('3 months', '3 months'), ('6 months', '6 months'), ('1 year', '1 year')], max_length=16)),
                ('status', models.CharField(choices=[('Saved', 'Saved'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Deleted', 'Deleted')], default='Saved', max_length=32)),
                ('is_author', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cure_reports', to=settings.AUTH_USER_MODEL)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='core.report')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='comorbidity',
            field=models.ManyToManyField(blank=True, related_name='+', to='core.Comorbidity'),
        ),
        migrations.AddField(
            model_name='patient',
            name='race',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='core.Race'),
        ),
        migrations.AddField(
            model_name='report',
            name='adverse_events_outcome',
            field=models.ManyToManyField(blank=True, to='core.AdverseEventsOutcome'),
        ),
    ]
