# Generated by Django 4.0.1 on 2022-03-10 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adverseeventsoutcome_comorbidity_organism_race_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='race',
            field=models.ManyToManyField(blank=True, related_name='+', to='core.Race'),
        ),
        migrations.CreateModel(
            name='UseDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=128)),
                ('regimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='use_drug', to='core.regimen')),
            ],
        ),
    ]
