# Generated by Django 4.0.1 on 2022-03-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_patient_race_usedrug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='severity',
        ),
        migrations.AddField(
            model_name='report',
            name='adverse_events',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='report',
            name='have_adverse_events',
            field=models.BooleanField(default=False, verbose_name='Did the patient experience any adverse events?'),
        ),
        migrations.AddField(
            model_name='report',
            name='relapse',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='site_of_infection',
            field=models.CharField(blank=True, help_text='Site of infection', max_length=255, verbose_name='Site of infection'),
        ),
        migrations.AddField(
            model_name='report',
            name='unusual',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='report',
            name='when_outcome',
            field=models.CharField(blank=True, choices=[('After a period of follow-up', 'After a period of follow-up'), ('At the time the treatment was completed', 'At the time the treatment was completed'), ('While the patient was still on treatment', 'While the patient was still on treatment')], max_length=128),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='delivery_gestational_age',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('1 Week', '1 Week'), ('2 Weeks', '2 Weeks'), ('3 Weeks', '3 Weeks'), ('4 Weeks', '4 Weeks'), ('5 Weeks', '5 Weeks'), ('6 Weeks', '6 Weeks'), ('7 Weeks', '7 Weeks'), ('8 Weeks', '8 Weeks'), ('9 Weeks', '9 Weeks'), ('10 Weeks', '10 Weeks'), ('11 Weeks', '11 Weeks'), ('12 Weeks', '12 Weeks'), ('13 Weeks', '13 Weeks'), ('14 Weeks', '14 Weeks'), ('15 Weeks', '15 Weeks'), ('16 Weeks', '16 Weeks'), ('17 Weeks', '17 Weeks'), ('18 Weeks', '18 Weeks'), ('19 Weeks', '19 Weeks'), ('20 Weeks', '20 Weeks'), ('21 Weeks', '21 Weeks'), ('22 Weeks', '22 Weeks'), ('23 Weeks', '23 Weeks'), ('24 Weeks', '24 Weeks'), ('25 Weeks', '25 Weeks'), ('26 Weeks', '26 Weeks'), ('27 Weeks', '27 Weeks'), ('28 Weeks', '28 Weeks'), ('29 Weeks', '29 Weeks'), ('30 Weeks', '30 Weeks'), ('31 Weeks', '31 Weeks'), ('32 Weeks', '32 Weeks'), ('33 Weeks', '3 Weeks'), ('34 Weeks', '34 Weeks'), ('35 Weeks', '35 Weeks'), ('36 Weeks', '36 Weeks'), ('37 Weeks', '37 Weeks'), ('38 Weeks', '38 Weeks'), ('39 Weeks', '39 Weeks'), ('40 Weeks', '40 Weeks'), ('41 Weeks', '41 Weeks'), ('42 Weeks', '42 Weeks'), ('42 Weeks', '42 Weeks')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='treatment_gestational_age',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('1 Week', '1 Week'), ('2 Weeks', '2 Weeks'), ('3 Weeks', '3 Weeks'), ('4 Weeks', '4 Weeks'), ('5 Weeks', '5 Weeks'), ('6 Weeks', '6 Weeks'), ('7 Weeks', '7 Weeks'), ('8 Weeks', '8 Weeks'), ('9 Weeks', '9 Weeks'), ('10 Weeks', '10 Weeks'), ('11 Weeks', '11 Weeks'), ('12 Weeks', '12 Weeks'), ('13 Weeks', '13 Weeks'), ('14 Weeks', '14 Weeks'), ('15 Weeks', '15 Weeks'), ('16 Weeks', '16 Weeks'), ('17 Weeks', '17 Weeks'), ('18 Weeks', '18 Weeks'), ('19 Weeks', '19 Weeks'), ('20 Weeks', '20 Weeks'), ('21 Weeks', '21 Weeks'), ('22 Weeks', '22 Weeks'), ('23 Weeks', '23 Weeks'), ('24 Weeks', '24 Weeks'), ('25 Weeks', '25 Weeks'), ('26 Weeks', '26 Weeks'), ('27 Weeks', '27 Weeks'), ('28 Weeks', '28 Weeks'), ('29 Weeks', '29 Weeks'), ('30 Weeks', '30 Weeks'), ('31 Weeks', '31 Weeks'), ('32 Weeks', '32 Weeks'), ('33 Weeks', '3 Weeks'), ('34 Weeks', '34 Weeks'), ('35 Weeks', '35 Weeks'), ('36 Weeks', '36 Weeks'), ('37 Weeks', '37 Weeks'), ('38 Weeks', '38 Weeks'), ('39 Weeks', '39 Weeks'), ('40 Weeks', '40 Weeks'), ('41 Weeks', '41 Weeks'), ('42 Weeks', '42 Weeks'), ('42 Weeks', '42 Weeks')], help_text='The gestational age in week at the time of the treatment.', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='outcome',
            field=models.CharField(blank=True, choices=[('Patient was cured/recovered', 'Patient was cured/recovered'), ('Patient improved', 'Patient improved'), ("Patient's condition was unchanged", "Patient's condition was unchanged"), ('Patient deteriorated', 'Patient deteriorated'), ('Patient died', 'Patient died'), ('Treatment was terminated due to adverse events', 'Treatment was terminated due to adverse events'), ('Unknown', 'Unknown')], help_text="What was the patient's outcome?", max_length=128),
        ),
    ]
