# Generated by Django 4.0.1 on 2022-03-14 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_report_previous_drugs_report_resistant_drugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='core.disease'),
        ),
    ]
