# Generated by Django 4.0.1 on 2022-03-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_attachedimage'),
        ('core', '0007_article_disease'),
    ]

    operations = [
    ]
