# Generated by Django 4.0.1 on 2022-03-27 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_0004_attachedimage_0007_article_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_articles', to='core.article'),
        ),
        migrations.AlterField(
            model_name='clinicaltrial',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='howdiagnosisanswer',
            name='value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='site_of_disease',
            field=models.CharField(blank=True, help_text='Site of infection.', max_length=255, null=True, verbose_name='Site of Infection'),
        ),
        migrations.AlterField(
            model_name='report',
            name='site_of_infection',
            field=models.CharField(blank=True, help_text='Site of infection', max_length=255, null=True, verbose_name='Site of infection'),
        ),
        migrations.AlterField(
            model_name='whynewwayanswer',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
