# Generated by Django 4.0.1 on 2022-03-30 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_changes_caused_by_data_move'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clinicaltrial',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_patient_number',
        ),
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
        migrations.RemoveField(
            model_name='article',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='markdown',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='markdown',
        ),
        migrations.AddField(
            model_name='article',
            name='publication_type',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='attachedimage',
            name='caption',
            field=models.TextField(blank=True, help_text='Caption for the image', null=True),
        ),
        migrations.AddField(
            model_name='attachedimage',
            name='reviewed',
            field=models.BooleanField(default=False, help_text='If the image had already been reviewed'),
        ),
        migrations.AddField(
            model_name='attachedimage',
            name='reviewer',
            field=models.ForeignKey(help_text='User account that reviewed the image.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='interventions',
            field=models.CharField(blank=True, help_text='Interventions, up to 255 characters long.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='locations',
            field=models.CharField(blank=True, help_text='Locations, up to 255 characters long.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_end',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_time',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='attachedimage',
            name='image_name',
            field=models.CharField(default='attached-image-filler.jpg', help_text='The filename that will be displayed. Filler until the file is approved.', max_length=100),
        ),
        migrations.AlterField(
            model_name='attachedimage',
            name='real_name',
            field=models.CharField(help_text='The filename of the image in the S3.', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(help_text='User account that created this content.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='author',
            field=models.ForeignKey(help_text='User account that created this content.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.RemoveField(
            model_name='clinicaltrial',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='clinicaltrial',
            name='sponsor_type',
        ),
        migrations.RemoveField(
            model_name='clinicaltrial',
            name='study_type',
        ),
    ]
