# Generated by Django 4.0.1 on 2022-03-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_clinicaltrial_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachedimage',
            old_name='image_name',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='patient',
            name='comorbidity',
            field=models.ManyToManyField(blank=True, related_name='comorbidities', to='core.Comorbidity'),
        ),
    ]
