# Generated by Django 4.0.1 on 2022-04-01 18:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_image_name_attachedimage_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whynewwayanswer',
            name='report',
        ),
        migrations.RemoveField(
            model_name='report',
            name='cross_linked_diseases',
        ),
        migrations.AddField(
            model_name='report',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='how_diagnosis',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, help_text='Diagnosis', max_length=16, null=True, size=None),
        ),
        migrations.AddField(
            model_name='report',
            name='how_outcome',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='organisms',
            field=models.ManyToManyField(blank=True, help_text='What drug(s) did you use in a new way?', null=True, related_name='reports_organisms', to='core.Organism'),
        ),
        migrations.AddField(
            model_name='report',
            name='why_new_way',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, help_text='Treatment challenges', max_length=16, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='drug',
            name='rxnorm_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='patient',
            name='race',
        ),
        migrations.AddField(
            model_name='patient',
            name='race',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, help_text='Race(s) of the patient', max_length=16, null=True, size=None),
        ),
        migrations.RemoveField(
            model_name='report',
            name='adverse_events_outcome',
        ),
        migrations.AddField(
            model_name='report',
            name='adverse_events_outcome',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, help_text='Adverse events outcome', max_length=16, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='HowDiagnosisAnswer',
        ),
        migrations.DeleteModel(
            name='Race',
        ),
        migrations.DeleteModel(
            name='WhyNewWayAnswer',
        ),
    ]
