# Generated by Django 4.0.1 on 2022-04-01 21:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_whynewwayanswer_report_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdverseEventsOutcome',
        ),
        migrations.AddField(
            model_name='regimen',
            name='use_drug',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, help_text='Use drug', max_length=16, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='how_outcome',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, help_text='Diagnosis', max_length=16, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='outcome',
            field=models.CharField(blank=True, choices=[('Patient was cured/recovered', 'Patient was cured/recovered'), ('Patient improved', 'Patient improved'), ("Patient's condition was unchanged", "Patient's condition was unchanged"), ('Patient deteriorated', 'Patient deteriorated'), ('Patient died', 'Patient died'), ('Treatment was terminated due to adverse events', 'Treatment was terminated due to adverse events'), ('Outcome is unknown/not yet determined', 'Outcome is unknown/not yet determined')], help_text="What was the patient's outcome?", max_length=128),
        ),
        migrations.DeleteModel(
            name='UseDrug',
        ),
    ]
