# Generated by Django 4.0.1 on 2022-04-01 21:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_adverseeventsoutcome_regimen_use_drug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regimen',
            name='use_drug',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, help_text='Use drug', max_length=16, null=True, size=None),
        ),
    ]
