# Generated by Django 4.0.1 on 2022-04-04 16:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_regimen_use_drug'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='outcome_followup',
            field=models.CharField(blank=True, help_text='Outcome timing', max_length=64, null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='neonate',
            name='pregnancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neonates', to='core.pregnancy'),
        ),
        migrations.AlterField(
            model_name='report',
            name='how_diagnosis',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, help_text='Diagnosis', max_length=16, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='why_new_way',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, help_text='Treatment challenges', max_length=16, null=True, size=None),
        ),
    ]
