# Generated by Django 4.0.1 on 2022-04-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age_group',
            field=models.CharField(blank=True, choices=[('<1 year', '<1 year'), ('1-5 years', '1-5 years'), ('6-10 years', '6-10 years'), ('11-15 years', '11-15 years'), ('16-20 years', '16-20 years'), ('21-30 years', '21-30 years'), ('31-40 years', '31-40 years'), ('41-50 years', '41-50 years'), ('51-60 years', '51-60 years'), ('61-70 years', '61-70 years'), ('71-80 years', '71-80 years'), ('81-89 years', '81-89 years'), ('90+ years', '90+ years')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='comorbidity',
            field=models.ManyToManyField(blank=True, null=True, related_name='comorbidities', to='core.Comorbidity'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='other_coinfections',
            field=models.CharField(blank=True, help_text='Up to 255 characters long.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Not specified', 'Not specified')], max_length=64, null=True),
        ),
    ]
