# Generated by Django 4.0.1 on 2022-04-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_patient_age_group_alter_patient_comorbidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaltrial',
            name='clinical_trials_gov_id',
            field=models.CharField(max_length=15),
        ),
    ]
