# Generated by Django 4.0.1 on 2022-04-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_patient_age_group_alter_patient_comorbidity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='affiliation',
            new_name='specialty',
        ),
        migrations.AlterField(
            model_name='profile',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
