# Generated by Django 4.0.1 on 2022-04-12 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_clinicaltrial_clinical_trials_gov_id'),
        ('core', '0020_rename_affiliation_profile_specialty_and_more'),
    ]

    operations = [
    ]
