# Generated by Django 4.0.1 on 2022-04-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_newsfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attachedimage',
            name='url',
            field=models.CharField(default='attached-image-filler-content.jpg', help_text='The filename that will be displayed. Filler until the file is approved.', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(blank=True, default='attached-image-filler-profile.jpg', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='qualification',
            field=models.CharField(choices=[('Researcher', 'Researcher'), ('Microbiologist', 'Microbiologist'), ('Pharmacologist', 'Pharmacologist'), ('Immunologist', 'Immunologist'), ('Social Worker', 'Social Worker'), ('Epidemiologist', 'Epidemiologist'), ('Health Policy Specialist', 'Health Policy Specialist'), ('Regulator', 'Regulator'), ('Lawyer', 'Lawyer'), ('Informaticist/Data Scientist', 'Informaticist/Data Scientist'), ('Medical Doctor', 'Medical Doctor'), ('Nurse Practitioner', 'Nurse Practitioner'), ('Physician Assistant', 'Physician Assistant'), ('Nurse', 'Nurse'), ('Community Health Worker', 'Community Health Worker'), ('Pharmacist', 'Pharmacist'), ('Public Health Specialist', 'Public Health Specialist'), ('Other Healthcare Professional', 'Other Healthcare Professional')], default='Other Healthcare Professional', max_length=30),
        ),
    ]
