# Generated by Django 4.0.4 on 2022-04-28 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_profile_institution_alter_attachedimage_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnseenNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pushnotification', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('newsfeed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.newsfeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unseennews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
