# Generated by Django 4.0.4 on 2022-04-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_unseennews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qualification',
            field=models.CharField(choices=[('Researcher', 'Researcher'), ('Microbiologist', 'Microbiologist'), ('Pharmacologist', 'Pharmacologist'), ('Immunologist', 'Immunologist'), ('Social Worker', 'Social Worker'), ('Epidemiologist', 'Epidemiologist'), ('Health Policy Specialist', 'Health Policy Specialist'), ('Regulator', 'Regulator'), ('Lawyer', 'Lawyer'), ('Informaticist/Data Scientist', 'Informaticist/Data Scientist'), ('Medical Doctor', 'Medical Doctor'), ('Nurse Practitioner', 'Nurse Practitioner'), ('Physician Assistant', 'Physician Assistant'), ('Nurse', 'Nurse'), ('Community Health Worker', 'Community Health Worker'), ('Pharmacist', 'Pharmacist'), ('Public Health Specialist', 'Public Health Specialist'), ('Other Healthcare Professional', 'Other Healthcare Professional'), ('Patient', 'Patient'), ('Parent', 'Parent'), ('Caregiver', 'Caregiver'), ('Community Member', 'Community Member'), ('Advocate', 'Advocate')], default='Other Healthcare Professional', max_length=30),
        ),
    ]
