# Generated by Django 4.0.4 on 2022-04-28 18:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_profile_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='how_diagnosis',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1096), blank=True, default=list, help_text='Diagnosis', max_length=16, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='why_new_way',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1096), blank=True, default=list, help_text='Treatment challenges', max_length=16, null=True, size=None),
        ),
    ]
