# Generated by Django 4.0.4 on 2022-05-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_report_drugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='drugs',
            field=models.ManyToManyField(blank=True, help_text='What drug(s) did you use in a new way?', related_name='reports', through='core.Regimen', to='core.drug'),
        ),
    ]
