# Generated by Django 4.0.4 on 2022-05-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_report_drugs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicaltrial',
            old_name='status',
            new_name='ct_status',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Submitted', 'Submitted'), ('Saved', 'Saved'), ('Rejected', 'Rejected'), ('Deleted', 'Deleted')], default='Submitted', max_length=32),
        ),
        migrations.AddField(
            model_name='discussion',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Submitted', 'Submitted'), ('Saved', 'Saved'), ('Rejected', 'Rejected'), ('Deleted', 'Deleted')], default='Submitted', max_length=32),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Submitted', 'Submitted'), ('Saved', 'Saved'), ('Rejected', 'Rejected'), ('Deleted', 'Deleted')], default='Submitted', max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorited_articles',
            field=models.ManyToManyField(blank=True, help_text='List of Articles the user is interested in.', related_name='profiles', to='core.article'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorited_clinical_trials',
            field=models.ManyToManyField(blank=True, help_text='List of ClinicalTrials the user is interested in.', related_name='profiles', to='core.clinicaltrial'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorited_discussions',
            field=models.ManyToManyField(blank=True, help_text='List of discussions the user is interested in.', related_name='profiles', to='core.discussion'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorited_diseases',
            field=models.ManyToManyField(blank=True, help_text='List of diseases the user is interested in.', related_name='profiles', to='core.disease'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorited_drugs',
            field=models.ManyToManyField(blank=True, help_text='List of drugs the user is interested in.', related_name='profiles', to='core.drug'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorited_events',
            field=models.ManyToManyField(blank=True, help_text='List of Events the user is interested in.', related_name='profiles', to='core.event'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorited_reports',
            field=models.ManyToManyField(blank=True, help_text='List of reports the user is interested in.', related_name='profiles', to='core.report'),
        ),
    ]
