# Generated by Django 4.0.4 on 2022-05-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_rename_status_clinicaltrial_ct_status_article_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaltrial',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Submitted', 'Submitted'), ('Saved', 'Saved'), ('Rejected', 'Rejected'), ('Deleted', 'Deleted')], default='Submitted', max_length=32),
        ),
    ]
