# Generated by Django 4.0.4 on 2022-05-19 14:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_attachedimage_real_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True, null=True), blank=True, default=[], null=True, size=None),
        ),
    ]
