# Generated by Django 4.0.4 on 2022-05-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_article_publication_name_alter_report_organisms'),
        ('core', '0034_profile_liked_comments'),
    ]

    operations = [
    ]
