# Generated by Django 4.0.4 on 2022-05-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_merge_20220519_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_url',
            field=models.URLField(blank=True, max_length=1096, null=True),
        ),
    ]
