# Generated by Django 4.0.4 on 2022-06-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_report_extrapulmonary_site_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='site_of_infection',
            new_name='site_of_tuberculosis_infection',
        ),
    ]
