# Generated by Django 4.0.4 on 2022-06-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_report_extrapulmonary_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(blank=True, default='attached-image-filler-profile.jpg', max_length=255, null=True),
        ),
    ]
