# Generated by Django 4.0.4 on 2022-06-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_profile_profile_image'),
        ('core', '0038_rename_site_of_infection_report_site_of_tuberculosis_infection'),
    ]

    operations = [
    ]
