# Generated by Django 4.0.4 on 2022-06-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_merge_20220606_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
