# Generated by Django 4.0.4 on 2022-06-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_profile_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comorbidity',
            options={'verbose_name_plural': 'Comorbidities'},
        ),
        migrations.AlterModelOptions(
            name='pregnancy',
            options={'verbose_name_plural': 'Pregnancies'},
        ),
        migrations.AlterField(
            model_name='article',
            name='published_authors',
            field=models.TextField(blank=True, help_text="A list of authors' names. Up to 256 characters.", max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, help_text='Article title, up to 255 characters.', max_length=1024, null=True, verbose_name='Article Title'),
        ),
        migrations.AlterField(
            model_name='attachedimage',
            name='url',
            field=models.CharField(default='attached_image_filler_content.jpg', help_text='The filename that will be displayed. Filler until the file is approved.', max_length=256),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='qualification',
            field=models.CharField(choices=[('Researcher', 'Researcher'), ('Microbiologist', 'Microbiologist'), ('Pharmacologist', 'Pharmacologist'), ('Immunologist', 'Immunologist'), ('Social Worker', 'Social Worker'), ('Epidemiologist', 'Epidemiologist'), ('Health Policy Specialist', 'Health Policy Specialist'), ('Regulator', 'Regulator'), ('Lawyer', 'Lawyer'), ('Informaticist/Data Scientist', 'Informaticist/Data Scientist'), ('Medical Doctor', 'Medical Doctor'), ('Nurse Practitioner', 'Nurse Practitioner'), ('Physician Assistant', 'Physician Assistant'), ('Nurse', 'Nurse'), ('Community Health Worker', 'Community Health Worker'), ('Pharmacist', 'Pharmacist'), ('Public Health Specialist', 'Public Health Specialist'), ('Other Healthcare Professional', 'Other Healthcare Professional'), ('Patient', 'Patient'), ('Parent', 'Parent'), ('Caregiver', 'Caregiver'), ('Community Member', 'Community Member'), ('Advocate', 'Advocate'), ('CURE Admin', 'CURE Admin')], default='Other Healthcare Professional', max_length=30),
        ),
    ]
