# Generated by Django 4.0.4 on 2022-07-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_comorbidity_options_alter_pregnancy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
