# Generated by Django 4.0.4 on 2022-07-12 19:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_article_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='comorbidity',
            field=models.ManyToManyField(blank=True, related_name='comorbidities', to='core.comorbidity'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='organisms',
            field=models.ManyToManyField(blank=True, related_name='reports_organisms', to='core.organism'),
        ),
    ]
