# Generated by Django 4.0.4 on 2022-07-23 14:54

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text

from server.apps.core.constants import JOURNAL


def update_blank_publication_type(apps, schema):
    """ Update all empty Article.publication_type to 'journal' """
    Article = apps.get_model('core', 'Article')
    Article.objects.filter(publication_type=None).update(publication_type=JOURNAL)

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0043_get_rid_of_warnings'),
    ]

    operations = [
        migrations.RunPython(update_blank_publication_type),
        migrations.DeleteModel(
            name='JournalArticle',
        ),
        migrations.DeleteModel(
            name='NewsArticle',
        ),
        migrations.CreateModel(
            name='CureUser',
            fields=[
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('first_name'), django.db.models.functions.text.Lower('last_name')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_type',
            field=models.CharField(choices=[('news', 'news'), ('journal', 'journal')], max_length=16),
        ),
        migrations.AlterField(
            model_name='attachedimage',
            name='url',
            field=models.CharField(default='attached-image-filler-content.jpg', help_text='The filename that will be displayed. Filler until the file is approved.', max_length=256),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='core.cureuser'),
        ),
        migrations.AlterField(
            model_name='clinicaltrial',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinicaltrials', to='core.cureuser'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(help_text='User account that created this content.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cureuser'),
        ),
        migrations.AlterField(
            model_name='curereport',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cure_reports', to='core.cureuser'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='author',
            field=models.ForeignKey(help_text='User account that created this content.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cureuser'),
        ),
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.cureuser'),
        ),
    ]
