# Generated by Django 4.0.4 on 2022-08-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_report_sample_alter_patient_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='extra_fields',
            field=models.JSONField(default=dict, help_text='JSON array for any additional report fields.', null=True),
        ),
    ]
