# Generated by Django 4.0.4 on 2022-08-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_report_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='curereport',
            name='report_type',
            field=models.CharField(default='', max_length=16),
        ),
    ]
