# Generated by Django 4.0.4 on 2022-08-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_curereport_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='organisms',
            field=models.ManyToManyField(blank=True, help_text='Organisms that are believed to cause the Disease', related_name='disease', to='core.organism'),
        ),
    ]
