# Generated by Django 4.0.4 on 2022-08-17 19:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_link_disease_and_organisms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='race',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=75), blank=True, default=list, help_text='Race(s) of the patient', max_length=16, null=True, size=None),
        ),
    ]
