# Generated by Django 4.0.4 on 2022-08-24 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_patient_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProposedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubmed_id', models.IntegerField(blank=True, help_text='PubMed ID of the article.', null=True)),
                ('article_url', models.URLField(blank=True, max_length=1096, null=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Rejected', 'Rejected')], default='Submitted', max_length=32)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_articles', to='core.cureuser')),
            ],
        ),
    ]
