# Generated by Django 4.0.7 on 2022-08-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_userproposedarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='cross_linked_diseases',
            field=models.ManyToManyField(blank=True, null=True, related_name='cross_linked_reports', to='core.disease'),
        ),
    ]
