# Generated by Django 4.0.7 on 2022-08-31 12:58
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_add_report__cross_linked_diseases'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clinicaltrial',
            unique_together={('disease', 'clinical_trials_gov_id')},
        ),
    ]
