# Generated by Django 4.0.4 on 2022-08-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_add_report__cross_linked_diseases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('Hispanic/Latino', 'Hispanic/Latino'), ('Not Hispanic/Latino', 'Not Hispanic/Latino'), ('Unknown', 'Unknown'), ('Not applicable', 'Not applicable')], max_length=64, null=True),
        ),
    ]
