# Generated by Django 4.0.4 on 2022-08-31 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_remove_ct_duplicates'),
        ('core', '0054_alter_curereport_report_type_and_more'),
    ]

    operations = [
    ]
