# Generated by Django 4.0.1 on 2022-03-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Datetime when the object was created.')),
                ('user', models.CharField(blank=True, help_text='Username or none of the user making the request.', max_length=128, null=True)),
                ('path', models.CharField(help_text='Path being requested.', max_length=256)),
                ('method', models.CharField(help_text='Method of the request, for ex. GET, POST, etc', max_length=10)),
                ('arguments', models.TextField(help_text='Will hold values from QueryString or request.POST.')),
            ],
        ),
    ]
