"""Local Python interface for RDAS EPI/NHS endpoint replacements."""

from .classifier import (
    DEFAULT_MODEL,
    DependencyError,
    EpiClassifyTextPipeline,
    classify_text,
    clear_pipeline_cache,
    get_pipeline,
    postEpiClassifyText,
    post_epi_classify_text,
)
from .endpoints import (
    EPI_API_URI,
    EPI_CLASSIFY_API,
    EPI_EXTRACT_API,
    NHS_PREDICT_API,
    local_post,
)
from .extractor import (
    DEFAULT_EXTRACT_MODEL,
    EpiExtractPipeline,
    ExtractionDependencyError,
    clear_extract_cache,
    get_extract_pipeline,
    postEpiExtractText,
    post_epi_extract_text,
)
from .nhs import (
    DEFAULT_NHS_MAX_LENGTH,
    DEFAULT_NHS_MODEL,
    NHS_MODEL_PATH_ENV_NAMES,
    NhsArticlePredictionPipeline,
    NhsDependencyError,
    NhsPredictionUnavailable,
    clear_nhs_pipeline_cache,
    clear_nhs_predictor,
    configure_nhs_predictor,
    get_nhs_pipeline,
    iter_predict_article,
    predict,
    predict_article,
)

__all__ = [
    "DEFAULT_EXTRACT_MODEL",
    "DEFAULT_MODEL",
    "DEFAULT_NHS_MAX_LENGTH",
    "DEFAULT_NHS_MODEL",
    "DependencyError",
    "EPI_API_URI",
    "EPI_CLASSIFY_API",
    "EPI_EXTRACT_API",
    "EpiExtractPipeline",
    "EpiClassifyTextPipeline",
    "ExtractionDependencyError",
    "NHS_PREDICT_API",
    "NHS_MODEL_PATH_ENV_NAMES",
    "NhsArticlePredictionPipeline",
    "NhsDependencyError",
    "NhsPredictionUnavailable",
    "classify_text",
    "clear_extract_cache",
    "clear_nhs_pipeline_cache",
    "clear_nhs_predictor",
    "clear_pipeline_cache",
    "configure_nhs_predictor",
    "get_extract_pipeline",
    "get_nhs_pipeline",
    "get_pipeline",
    "iter_predict_article",
    "local_post",
    "postEpiExtractText",
    "postEpiClassifyText",
    "post_epi_extract_text",
    "post_epi_classify_text",
    "predict",
    "predict_article",
]
