
# SELECT distinct search_term FROM rdas_db.publication_gard_searchterm_pubmed_mapping where length(search_term)<=8 order by search_term;

exclude_words = [
    "anes",
    "arca",
    "arms",
    "canvas",
    "cass",
    "char",
    "clam",
    "COVE",
    "dandy",
    "dish",
    "dress",
    "dublin",
    "edict",
    "ever",
    "face",
    "GAVE",
    "glass",
    "GLOW",
    "haff",
    "igad1",
    "imam",
    "lamb",
    "Lota",
    "locus",
    "matins",
    "mirage",
    "mvp1",
    "paca",
    "pais",
    "pale",
    "papa",
    "pda1",
    "pest",
    "PLAN",
    "plack",
    "plaid",
    "plasma",
    "prop",
    "rich",
    "script",
    "settle",
    "smith",
    "soft",
    "stale",
    "STAR",
    "sudan",
    "sybil",
    "thymus",
    "thyroid",
    "wells",
    "whims",
]

NOT_AVAILAVLE = 'N/A'