# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UuBpDcw1AprfHKHnJ6BL8xGmfCApGUAP
"""

from src import functions

def main():
    functions.Find()

if __name__ == '__main__':
    main()